'use client';
import {Users,ArrowUpRight,CalendarDays,Wallet,FileText,Activity,AlertCircle} from 'lucide-react';
import {type Workspace,type Row,money,hours,allocationBalance,monthEnd} from '@/lib/domain';
import {Picker,DataTable,Badge,niceMonth} from './peoplepay-ui';
export default function Dashboard({s,period,setPeriod,department,setDepartment,employeeType,setEmployeeType,navigate}:{s:Workspace;period:string;setPeriod:(s:string)=>void;department:string;setDepartment:(s:string)=>void;employeeType:string;setEmployeeType:(s:string)=>void;navigate:(view:string,id?:string)=>void}){
 const employees=s.employees.filter(e=>(department==='All'||e.department===department)&&(employeeType==='All'||e.type===employeeType)),ids=new Set(employees.map(e=>e.id)),departments=[...new Set(s.employees.map(e=>e.department))];
 const selectedRuns=s.payruns.filter(r=>r.period===period),slips=selectedRuns.flatMap(r=>r.slips.map((p:Row)=>({...p,status:r.status}))).filter(p=>ids.has(p.employeeId));
 const paid=slips.filter(p=>p.status==='Paid').reduce((n,p)=>n+p.net,0),net=slips.reduce((n,p)=>n+p.net,0);
 const attendance=s.attendance.filter(a=>ids.has(a.employeeId)&&a.date.startsWith(period)),present=attendance.filter(a=>a.checkIn),complete=present.filter(a=>a.checkOut),missing=present.length-complete.length;
 const late=present.filter(a=>{const e=s.employees.find(e=>e.id===a.employeeId),sc=s.schedules.find(sc=>sc.id===e?.scheduleId);return a.checkIn>(sc?.start||'09:00');}).length;
 const health=attendance.length?Math.round(complete.length/attendance.length*100):0;
 const requests=s.requests.filter(r=>ids.has(r.employeeId)&&r.start<=monthEnd(period)&&r.end>=period+'-01');
 const approvedDays=requests.filter(r=>r.status==='Approved'&&s.leaveTypes.find(t=>t.id===r.typeId)?.unit==='Days').reduce((n,r)=>n+Math.round((Date.parse(r.end<monthEnd(period)?r.end:monthEnd(period))-Date.parse(r.start>period+'-01'?r.start:period+'-01'))/86400000)+1,0),pending=requests.filter(r=>r.status==='Pending').length;
 const trend=Array.from({length:6},(_,i)=>{const date=new Date(period+'-01T00:00:00Z');date.setUTCMonth(date.getUTCMonth()-5+i);const p=date.toISOString().slice(0,7);return {period:p,amount:s.payruns.filter(r=>r.period===p&&r.status==='Paid').flatMap(r=>r.slips).filter((p:Row)=>ids.has(p.employeeId)).reduce((n:number,p:Row)=>n+p.net,0)};});
 const max=Math.max(...trend.map(t=>t.amount),1),deptRows=departments.filter(d=>department==='All'||department===d).map(d=>({id:d,name:d,count:employees.filter(e=>e.department===d&&e.status==='Active').length,amount:slips.filter(p=>employees.find(e=>e.id===p.employeeId)?.department===d).reduce((n,p)=>n+p.gross,0)})),maxDept=Math.max(...deptRows.map(r=>r.amount),1);
 const bankMissing=employees.filter(e=>e.status==='Active'&&!e.bank),drafts=selectedRuns.filter(r=>r.status!=='Paid'&&r.employeeIds.some((id:string)=>ids.has(id))),expiring=s.contracts.filter(c=>ids.has(c.employeeId)&&c.end&&c.end.startsWith(period));
 const alerts=[...(drafts.length?[{id:'pay',title:`${drafts.length} payrun${drafts.length>1?'s':''} awaiting completion`,detail:niceMonth(period)+' · Review and process payroll',view:'payruns'}]:[]),...(pending?[{id:'leave',title:`${pending} time off requests to review`,detail:'Keep your team’s plans moving',view:'requests'}]:[]),...(bankMissing.length?[{id:'bank',title:`${bankMissing.length} missing bank account${bankMissing.length>1?'s':''}`,detail:bankMissing.map(e=>e.name).join(', '),view:'employees',employeeId:bankMissing[0].id}]:[]),...(expiring.length?[{id:'contract',title:`${expiring.length} contract${expiring.length>1?'s':''} expiring this month`,detail:'Review upcoming employment changes',view:'contracts'}]:[])];
 const months=[...new Set([...s.payruns.map(r=>r.period),period,'2026-10','2026-11','2026-12'])].sort().reverse();
 return <><div className="filterbar"><Picker label="Period" value={period} onChange={setPeriod} options={months.map(p=>({value:p,label:niceMonth(p)}))}/><Picker label="Department" value={department} onChange={setDepartment} options={[{value:'All',label:'All departments'},...departments]}/><Picker label="Employee type" value={employeeType} onChange={setEmployeeType} options={[{value:'All',label:'All employee types'},'Full-time','Contract','Intern']}/><small>OXP Pvt Ltd <span className="live-dot"/> Updated from workspace records</small></div>
 <div className="metrics">{[{name:'Total net salary paid',value:money(paid),sub:`${slips.filter(p=>p.status==='Paid').length} payslips paid this period`,Icon:Wallet},{name:'Payslips generated',value:slips.length,sub:`${slips.filter(p=>p.status!=='Paid').length} awaiting payment`,Icon:FileText},{name:'Average net salary',value:money(slips.length?net/slips.length:0),sub:'Across generated payslips',Icon:Users},{name:'Approved time off',value:approvedDays+' days',sub:pending+' requests awaiting approval',Icon:CalendarDays},{name:'Attendance health',value:health+'%',sub:complete.length+' complete / '+attendance.length+' records',Icon:Activity}].map(m=><section className="metric" key={m.name}><div>{m.name}<m.Icon size={16}/></div><strong>{m.value}</strong><small>{m.sub}</small></section>)}</div>
 <div className="dashboard-grid"><section className="panel"><div className="panel-head"><h2>Monthly net salary trend</h2><span className="tag">Paid salary</span></div><p className="muted">Six months of salary payments for the selected team</p><div className="bar-chart" role="img" aria-label={trend.map(t=>`${niceMonth(t.period)}: ${money(t.amount)}`).join('; ')}>{trend.map(t=><div key={t.period}><span>{money(t.amount)}</span><i style={{height:Math.max(3,t.amount/max*170)+'px'}}/><small>{niceMonth(t.period).split(' ')[0].slice(0,3)}</small></div>)}</div><div className="status-line"><span className="live-dot"/>Finalized payment history · {department==='All'?'All departments':department}</div></section><section className="panel"><div className="panel-head"><h2>Needs your attention</h2><span className="count">{alerts.length}</span></div>{alerts.length?alerts.map(a=><div className="attention" key={a.id}><AlertCircle/><div><button className="link" onClick={()=>navigate(a.view,a.employeeId)}>{a.title}<ArrowUpRight size={14}/></button><p>{a.detail}</p></div></div>):<div className="empty">You’re all caught up for this period.</div>}</section></div>
 <div className="section-grid"><section className="panel"><div className="panel-head"><h2>Salary cost by department</h2><span className="muted">Gross salary</span></div>{deptRows.map(d=><div className="department-row" key={d.id}><span>{d.name}</span><div className="track"><i style={{width:d.amount/maxDept*100+'%'}}/></div><b>{money(d.amount)}</b></div>)}{!slips.length&&<p className="muted">Compute a payrun to see this period’s salary costs.</p>}</section><section className="panel"><div className="panel-head"><h2>Attendance overview</h2><button className="link" onClick={()=>navigate('attendance')}>View records <ArrowUpRight size={14}/></button></div><div className="stat-row">{[['Present',present.length],['Late',late],['Absent',attendance.length-present.length],['Over 9 hours',attendance.filter(a=>hours(a)>9).length]].map(([l,n])=><div key={l}><strong>{n}</strong><small>{l}</small></div>)}</div><div className="status-line"><span>{missing} missing check-outs</span><span>{attendance.filter(a=>a.edited).length} manual edits</span></div><p className="note">Late entries are included in present totals. Absence counts use recorded absence entries; missing dates are not inferred.</p></section></div>
 <div className="section-grid"><section className="panel table-panel"><div className="panel-head"><h2>Time off overview</h2><CalendarDays size={17}/></div><DataTable rows={s.leaveTypes} columns={[{title:'Leave type',render:t=>t.name},{title:'Approved',render:t=>requests.filter(r=>r.typeId===t.id&&r.status==='Approved').reduce((n,r)=>n+(t.unit==='Hours'?r.duration:Math.round((Date.parse(r.end<monthEnd(period)?r.end:monthEnd(period))-Date.parse(r.start>period+'-01'?r.start:period+'-01'))/86400000)+1),0)+' '+t.unit.toLowerCase()},{title:'Pending',render:t=>requests.filter(r=>r.typeId===t.id&&r.status==='Pending').length},{title:'Available balance',render:t=>t.requiresAllocation?s.allocations.filter(a=>a.typeId===t.id&&ids.has(a.employeeId)&&a.start<=period+'-01'&&a.end>=monthEnd(period)).reduce((n,a)=>n+allocationBalance(s,a),0)+' '+t.unit.toLowerCase():'Not required'}]}/></section><section className="panel table-panel"><div className="panel-head"><h2>Department overview</h2><span className="tag">{employees.filter(e=>e.status==='Active').length} active employees</span></div><DataTable rows={deptRows} columns={[{title:'Department',render:d=>d.name},{title:'Headcount',render:d=>d.count},{title:'Salary cost',render:d=>money(d.amount)}]}/></section></div>
 <section className="panel table-panel"><div className="panel-head"><h2>Recent payruns</h2><button className="link" onClick={()=>navigate('payruns')}>All payruns <ArrowUpRight size={14}/></button></div><DataTable rows={s.payruns.filter(r=>r.period===period&&r.employeeIds.some((id:string)=>ids.has(id))).slice().reverse()} columns={[{title:'Payrun',render:r=><button className="link" onClick={()=>navigate('run',r.id)}>{r.name}</button>},{title:'Salary structure',render:r=>s.structures.find(st=>st.id===r.structureId)?.name},{title:'Employees',render:r=>r.employeeIds.filter((id:string)=>ids.has(id)).length},{title:'Net salary',render:r=>money(r.slips.filter((p:Row)=>ids.has(p.employeeId)).reduce((n:number,p:Row)=>n+p.net,0))},{title:'Status',render:r=><Badge value={r.status}/>}]} /></section></>;
}
