'use client';
import { useState } from 'react';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { Checkbox } from '@/components/ui/checkbox';
import { Field, Picker } from './peoplepay-ui';
import { type Row, type Workspace } from '@/lib/domain';
export const titles: Record<string, string> = { employees: 'Employees', contracts: 'Contracts', attendance: 'Attendance', requests: 'Time off requests', allocations: 'Allocations', leaveTypes: 'Time off types', rules: 'Salary rules', structures: 'Salary structures', schedules: 'Working schedules', payruns: 'Payruns', payslips: 'Payslips', overview: 'Payroll overview', run: 'Payrun', employee: 'Employee profile', users: 'System Users' };
export function defaults(collection: string, s: Workspace, employeeId?: string): Row {
  const employee = employeeId || s.employees[0]?.id || '', structure = s.structures[0]?.id || '', schedule = s.schedules[0]?.id || '';
  const records: Record<string, any> = { employees: { name: '', email: '', phone: '', department: 'Engineering', position: '', type: 'Full-time', status: 'Active', manager: 'Sara Khan', location: 'Mumbai', scheduleId: schedule, bank: '' }, contracts: { employeeId: employee, start: '2026-10-01', end: '', wage: 50000, structureId: structure, scheduleId: schedule, status: 'Running' }, attendance: { employeeId: employee, date: '2026-09-05', checkIn: '09:00', checkOut: '18:00' }, requests: { employeeId: employee, typeId: 'paid', start: '2026-09-14', end: '2026-09-14', duration: 1, reason: '', status: 'Pending' }, allocations: { employeeId: employee, typeId: 'paid', amount: 20, start: '2027-01-01', end: '2027-12-31', status: 'Pending' }, leaveTypes: { name: '', unit: 'Days', requiresAllocation: true }, rules: { name: '', code: '', category: 'Allowance', sequence: 40, method: 'Fixed', base: 'WAGE', value: 0, expression: '' }, structures: { name: '', ruleIds: [], active: true }, schedules: { name: '', days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'], start: '09:00', end: '18:00', breakHours: 1 }, users: { name: '', email: '', roleId: 'employee', employeeId: '', password: '', active: true } };
  return { id: '', ...records[collection] };
}
export default function RecordForm({ collection, initial, s, busy, onSave, onCancel }: { collection: string; initial: Row; s: Workspace; busy: boolean; onSave: (record: Row) => Promise<void>; onCancel: () => void }) {
  const [r, setR] = useState<Row>(initial), set = (key: string, value: any) => setR(old => ({ ...old, [key]: value }));
  const input = (key: string, label: string, type = 'text', required = true) => <Field key={key} label={label}><Input aria-label={label} type={type} required={required} value={r[key] ?? ''} onChange={e => set(key, e.target.value)} step={type === 'number' ? '0.01' : undefined} min={type === 'number' ? 0 : undefined} /></Field>;
  const pick = (key: string, label: string, options: (string | { value: string; label: string })[]) => <Field key={key} label={label}><Picker label={label} value={r[key] ?? ''} onChange={v => set(key, v)} options={options} /></Field>;
  const employeePick = () => pick('employeeId', 'Employee', s.employees.map(e => ({ value: e.id, label: e.name })));
  const schedulePick = () => pick('scheduleId', 'Working schedule', s.schedules.map(e => ({ value: e.id, label: e.name })));
  const structurePick = () => pick('structureId', 'Salary structure', s.structures.map(e => ({ value: e.id, label: e.name })));
  const typePick = () => pick('typeId', 'Time off type', s.leaveTypes.map(e => ({ value: e.id, label: e.name })));
  const rolePick = () => pick('roleId', 'System Role', [{ value: 'admin', label: 'Admin' }, { value: 'payroll_manager', label: 'HR Payroll Manager' }, { value: 'payroll_user', label: 'HR Payroll User' }, { value: 'hr_manager', label: 'HR Manager' }, { value: 'employee', label: 'Employee' }]);
  return <form onSubmit={e => { e.preventDefault(); void onSave(r); }}><div className="form-grid">
    {collection === 'employees' && <>{input('name', 'Full name')}{input('email', 'Work email', 'email')}{input('position', 'Job position')}{input('department', 'Department')}{pick('type', 'Employee type', ['Full-time', 'Contract', 'Intern'])}{pick('status', 'Status', ['Active', 'Archived'])}{input('manager', 'Manager', 'text', false)}{schedulePick()}{input('location', 'Work location', 'text', false)}{input('phone', 'Phone', 'tel', false)}{input('bank', 'Bank account reference', 'text', false)}</>}
    {collection === 'contracts' && <>{employeePick()}{input('wage', 'Monthly contract wage (INR)', 'number')}{input('start', 'Start date', 'date')}{input('end', 'End date (optional)', 'date', false)}{structurePick()}{schedulePick()}<p className="note field wide">Keep historical contracts. Contract date ranges cannot overlap. End an existing open-ended contract before adding its successor; payroll currently requires one contract covering the full month.</p></>}
    {collection === 'attendance' && <>{employeePick()}{input('date', 'Date', 'date')}{input('checkIn', 'Check-in', 'time', false)}{input('checkOut', 'Check-out', 'time', false)}<p className="note field wide">One record per employee per day. Leave both times empty to record absence. Worked hours are calculated from check-in and check-out.</p></>}
    {collection === 'requests' && <>{employeePick()}{typePick()}{input('start', 'Start date', 'date')}{input('end', 'End date', 'date')}{s.leaveTypes.find(t => t.id === r.typeId)?.unit === 'Hours' && input('duration', 'Requested hours', 'number')}{input('reason', 'Reason')}<p className="note field wide">This prototype counts calendar days inclusively. Requests consume the matching approved allocation only after approval.</p></>}
    {collection === 'allocations' && <>{employeePick()}{typePick()}{input('amount', 'Allocated days / hours', 'number')}{input('start', 'Valid from', 'date')}{input('end', 'Valid until', 'date')}<p className="note field wide">An allocation becomes available only after approval. A given employee and leave type can have one allocation per non-overlapping validity period.</p></>}
    {collection === 'leaveTypes' && <>{input('name', 'Type name')}{pick('unit', 'Unit', ['Days', 'Hours'])}<label className="check-label"><Checkbox checked={r.requiresAllocation} onCheckedChange={v => set('requiresAllocation', v)} />Requires an approved allocation</label></>}
    {collection === 'rules' && <>{input('name', 'Rule name')}{input('code', 'Code (uppercase)')}{pick('category', 'Category', ['Basic', 'Allowance', 'Deduction'])}{input('sequence', 'Execution sequence', 'number')}{pick('method', 'Computation', ['Fixed', 'Percentage', 'Formula'])}{r.method !== 'Formula' && input('value', r.method === 'Fixed' ? 'Amount (INR)' : 'Percentage', 'number')}{r.method === 'Percentage' && pick('base', 'Percentage base', [{ value: 'WAGE', label: 'Contract wage' }, ...s.rules.filter(x => x.id !== r.id && x.sequence < +r.sequence).map(x => ({ value: x.code, label: x.name + ' (' + x.code + ')' }))])}{r.method === 'Formula' && input('expression', 'Formula (e.g. BASIC * 0.1 + 2000)')}<p className="note field wide">Rules execute in sequence. Formulas support arithmetic, parentheses, WAGE, and earlier rule codes. Sample deductions demonstrate the engine; they are not statutory payroll rules.</p></>}
    {collection === 'structures' && <>{input('name', 'Structure name')}<label className="check-label"><Checkbox checked={r.active} onCheckedChange={v => set('active', v)} />Active</label><div className="field wide check-list"><span>Included salary rules</span>{s.rules.slice().sort((a, b) => a.sequence - b.sequence).map(rule => <label key={rule.id}><Checkbox checked={r.ruleIds.includes(rule.id)} onCheckedChange={v => set('ruleIds', v ? [...r.ruleIds, rule.id] : r.ruleIds.filter((id: string) => id !== rule.id))} />{rule.name}<small>{rule.code} · {rule.sequence}</small></label>)}</div></>}
    {collection === 'schedules' && <>{input('name', 'Schedule name')}{input('start', 'Shift start', 'time')}{input('end', 'Shift end', 'time')}{input('breakHours', 'Daily break (hours)', 'number')}<div className="field wide check-list"><span>Working days</span>{['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'].map(d => <label key={d}><Checkbox checked={r.days.includes(d)} onCheckedChange={v => set('days', v ? [...r.days, d] : r.days.filter((x: string) => x !== d))} />{d}</label>)}</div><p className="note field wide">Weekly hours are calculated from the selected days, shift duration, and daily break.</p></>}
    {collection === 'users' && <>{input('name', 'Full name')}{input('email', 'Work email', 'email')}{rolePick()}{pick('employeeId', 'Linked employee (optional)', [{ value: '', label: 'None (System Only)' }, ...s.employees.map(e => ({ value: e.id, label: `${e.name} (${e.department})` }))])}{input('password', initial.id ? 'Password (leave blank to keep unchanged)' : 'Initial password', 'password', !initial.id)}<label className="check-label"><Checkbox checked={r.active ?? true} onCheckedChange={v => set('active', v)} />Active user account</label><p className="note field wide">Accounts are created and assigned roles by an Admin only. Assign roles to enforce role-based access control.</p></>}
  </div><div className="modal-actions"><Button type="button" variant="outline" onClick={onCancel}>Cancel</Button><Button type="submit" disabled={busy}>{busy ? 'Saving…' : initial.id ? 'Save changes' : 'Create record'}</Button></div></form>;
}
