'use client';
import {useCallback,useEffect,useState} from 'react';
import {Layers,Plus,ChevronDown,ArrowUpRight,Clock3,LayoutGrid,List,Download,ArrowLeft,Check,RefreshCw,FileText,Search} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {DropdownMenu,DropdownMenuTrigger,DropdownMenuContent,DropdownMenuItem} from '@/components/ui/dropdown-menu';
import {Checkbox} from '@/components/ui/checkbox';
import {type Workspace,type Row,money,hours,activeContract,warnings,allocationBalance,monthEnd} from '@/lib/domain';
import {Avatar,Badge,DataTable,Field,Picker,niceMonth,downloadCsv} from '@/components/peoplepay-ui';
import Dashboard from '@/components/payroll-dashboard';
import RecordForm,{defaults,titles} from '@/components/record-form';

type Modal={kind:'form'|'request'|'allocation'|'wizard'|'slip'|'clock'|'about';collection?:string;record?:Row};
const descriptions:Record<string,string>={employees:'The people who make it all happen.',contracts:'Employment terms, current contracts, and the full history.',attendance:'Review presence, working hours, and attendance exceptions.',requests:'A little time away. A clear approval process.',allocations:'Leave entitlements, approvals, and available balances.',leaveTypes:'Set the policies behind every time off request.',schedules:'Define your team’s working week.',payruns:'From contract to payslip, one connected workflow.',payslips:'Every salary, with a clear breakdown.',structures:'Group the rules that shape employee pay.',rules:'Configure the calculation behind every salary component.'};

export default function Home(){
 const [s,setS]=useState<Workspace|null>(null),[revision,setRevision]=useState(0),[view,setView]=useState('overview'),[activeId,setActiveId]=useState(''),[filterId,setFilterId]=useState(''),[query,setQuery]=useState(''),[mode,setMode]=useState('grid'),[period,setPeriod]=useState('2026-09'),[department,setDepartment]=useState('All'),[employeeType,setEmployeeType]=useState('All'),[modal,setModal]=useState<Modal|null>(null),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[clockNow,setClockNow]=useState(new Date());
 const load=useCallback(async()=>{try{setError('');const r=await fetch('/api/workspace',{cache:'no-store'});const body=(await r.json()) as any;if(!r.ok)throw new Error(body.error);setS(body.data);setRevision(body.revision);}catch(e){setError((e as Error).message);}},[]);
 useEffect(()=>{void load();const timer=setInterval(()=>setClockNow(new Date()),30000);return()=>clearInterval(timer);},[load]);
 useEffect(()=>{const read=()=>{const [v,id]=window.location.hash.slice(1).split('/');if(v&&(titles[v]||v==='overview')){setView(v);setActiveId(decodeURIComponent(id||''));setFilterId('');}};read();window.addEventListener('hashchange',read);return()=>window.removeEventListener('hashchange',read);},[]);
 function navigate(v:string,id?:string){setView(v);setActiveId(id||'');setFilterId('');setQuery('');setModal(null);setError('');setMessage('');window.history.replaceState(null,'','#'+v+(id?'/'+encodeURIComponent(id):''));}
 function related(v:string,id:string){navigate(v);setFilterId(id);}
 async function act(action:string,payload:Record<string,any>={},success='Changes saved'):Promise<Workspace|null>{if(busy)return null;setBusy(true);setError('');setMessage('');try{const r=await fetch('/api/workspace',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,payload,revision})});const b=(await r.json()) as any;if(!r.ok)throw new Error(b.error||'Unable to save.');setS(b.data);setRevision(b.revision);setMessage(success);return b.data;}catch(e){setError((e as Error).message);return null;}finally{setBusy(false);}}
 useEffect(()=>{const ctx=(document as any).modelContext;if(!ctx?.registerTool)return;const controller=new AbortController();Promise.resolve(ctx.registerTool({name:'navigate_peoplepay',description:'Open a PeoplePay workspace screen without changing records.',inputSchema:{type:'object',properties:{screen:{type:'string',enum:['overview','employees','contracts','attendance','requests','allocations','payruns','payslips','rules','structures','schedules']}},required:['screen'],additionalProperties:false},annotations:{readOnlyHint:true},execute:({screen}:{screen:string})=>{if(!['overview','employees','contracts','attendance','requests','allocations','payruns','payslips','rules','structures','schedules'].includes(screen))throw new Error('Unknown screen.');navigate(screen);return {screen};}},{signal:controller.signal})).catch(()=>{});return()=>controller.abort();},[]);
 const employee=(id:string)=>s?.employees.find(e=>e.id===id),empName=(id:string)=>employee(id)?.name||'Unknown employee',structure=(id:string)=>s?.structures.find(t=>t.id===id)?.name||'Unknown structure',leaveType=(id:string)=>s?.leaveTypes.find(t=>t.id===id);
 function openForm(collection:string,record?:Row){if(!s)return;setError('');setModal({kind:'form',collection,record:record?structuredClone(record):defaults(collection,s,filterId||undefined)});}
 const saveRecord=async(record:Row)=>{const result=await act('save',{collection:modal!.collection,record});if(result)setModal(null);};
 const filtered=(list:Row[])=>list.filter(r=>(!filterId||r.employeeId===filterId)&&(!query||[r.name,r.email,r.department,r.position,r.code,empName(r.employeeId)].some(x=>String(x||'').toLowerCase().includes(query.toLowerCase()))));
 const activeEmployee=employee(activeId),run=s?.payruns.find(r=>r.id===activeId);
 const reviewedRecord=modal?.kind==='request'?s?.requests.find(r=>r.id===modal.record?.id):modal?.kind==='allocation'?s?.allocations.find(r=>r.id===modal.record?.id):null;
 const currentClock=s?.attendance.find(a=>a.employeeId==='e6'&&a.date===clockNow.toLocaleDateString('en-CA',{timeZone:'Asia/Kolkata'}));
 const signedIn=!!currentClock?.checkIn&&!currentClock?.checkOut;
 const allSlips=s?.payruns.flatMap(r=>r.slips.map((p:Row)=>({...p,runId:r.id,status:r.status})))||[];
 const topMenu=(label:string,items:string[])=> <DropdownMenu key={label}><DropdownMenuTrigger className={'nav-trigger '+(items.includes(view)?'active':'')}>{label}<ChevronDown size={13}/></DropdownMenuTrigger><DropdownMenuContent className="nav-dropdown">{items.map(v=><DropdownMenuItem key={v} onClick={()=>navigate(v)}>{titles[v]}</DropdownMenuItem>)}</DropdownMenuContent></DropdownMenu>;
 const cellEmployee=(r:Row)=><button className="employee-cell link" onClick={()=>navigate('employee',r.employeeId)}><Avatar name={empName(r.employeeId)}/><span>{empName(r.employeeId)}<small>{employee(r.employeeId)?.department}</small></span></button>;
 const attendanceStatus=(a:Row)=>!a.checkIn?'Absent':!a.checkOut?'Missing check-out':a.checkIn>(s?.schedules.find(sc=>sc.id===employee(a.employeeId)?.scheduleId)?.start||'09:00')?'Late':'Present';
 const runSlipColumns=[{title:'Employee',render:cellEmployee},{title:'Recorded days',render:(p:Row)=>p.workedDays},{title:'Basic',render:(p:Row)=>money(p.basic)},{title:'Gross',render:(p:Row)=>money(p.gross)},{title:'Deductions',render:(p:Row)=>money(p.deductions)},{title:'Net salary',render:(p:Row)=><b>{money(p.net)}</b>},{title:'Payslip',render:(p:Row)=><button className="link" onClick={()=>setModal({kind:'slip',record:p})}><FileText size={15}/> View</button>}];
 const exportPayroll=()=>{if(!s)return;downloadCsv('peoplepay-payroll.csv',[['Period','Employee','Department','Gross','Deductions','Net','Status'],...allSlips.filter(p=>p.period===period).map(p=>[p.period,empName(p.employeeId),employee(p.employeeId)?.department,p.gross,p.deductions,p.net,p.status])]);};
 return <><header className="topbar"><a href="#overview" className="brand" onClick={e=>{e.preventDefault();navigate('overview');}}><Layers size={25}/>peoplepay<span>360</span></a><nav aria-label="Main navigation"><button className={view==='overview'?'active':''} onClick={()=>navigate('overview')}>Overview</button>{topMenu('Employees',['employees'])}{topMenu('Contracts',['contracts','schedules'])}<button className={view==='attendance'?'active':''} onClick={()=>navigate('attendance')}>Attendance</button>{topMenu('Time Off',['requests','allocations','leaveTypes'])}{topMenu('Payroll',['payruns','payslips','structures','rules'])}</nav><div className="header-actions"><button className={'icon-button '+(signedIn?'clock-active':'')} aria-label="Open attendance check-in widget" onClick={()=>setModal({kind:'clock'})}><Clock3 size={20}/></button><button className="icon-button" aria-label="Prototype information" onClick={()=>setModal({kind:'about'})}><span className="avatar">NR</span></button></div></header>
 <main><div className="breadcrumb"><button className="link" onClick={()=>navigate('overview')}>Workspace</button><span>/</span>{titles[view]||'Overview'}<span className="demo-label">DEMO ADMIN</span></div>
 <div className="page-heading"><div><p className="eyebrow">{view==='overview'?'PEOPLE & OPERATIONS':'OXP PVT LTD'}</p><h1>{view==='overview'?'Your people. In perspective.':view==='employee'?activeEmployee?.name||'Employee':view==='run'?run?.name||'Payrun':titles[view]}</h1><p>{view==='overview'?'Payroll, attendance, and time off. All in one place.':descriptions[view]||'Connected records. Clear decisions.'}</p></div>{view==='overview'?<div className="heading-actions"><Button variant="outline" onClick={exportPayroll} disabled={!s}><Download/> Export</Button><Button disabled={!s} onClick={()=>{setError('');setModal({kind:'wizard'});}}><Plus/> New payrun</Button></div>:view==='employee'?<Button onClick={()=>activeEmployee&&openForm('employees',activeEmployee)}>Edit employee</Button>:view==='run'?<Button variant="outline" onClick={()=>navigate('payruns')}><ArrowLeft/> All payruns</Button>:view==='payslips'?<Button variant="outline" onClick={exportPayroll}><Download/> Export period</Button>:<Button disabled={!s} onClick={()=>view==='payruns'?setModal({kind:'wizard'}):openForm(view)}><Plus/> {view==='payruns'?'New payrun':'New record'}</Button>}</div>
 {error&&!modal&&<div className="error" role="alert">{error} <button className="link" onClick={()=>void load()}>Reload workspace</button></div>}{message&&!modal&&<div className="success" role="status">{message}</div>}
 {!s?<section className="panel"><h2>{error?'Workspace not available':'Opening your workspace…'}</h2><p className="muted">{error?'Initialize the local database using the README instructions, then reload.':'Loading employees, attendance, and payroll records.'}</p><Button variant="outline" onClick={()=>void load()}><RefreshCw/> Reload</Button></section>:<>
 {view==='overview'&&<Dashboard s={s} period={period} setPeriod={setPeriod} department={department} setDepartment={setDepartment} employeeType={employeeType} setEmployeeType={setEmployeeType} navigate={(v,id)=>id&&v==='employees'?navigate('employee',id):navigate(v,id)}/>}
 {!['overview','employee','run'].includes(view)&&<div className="toolbar"><Search size={18} color="#80939b"/><Input aria-label="Search records" placeholder={'Search '+(titles[view]||'records').toLowerCase()+'…'} value={query} onChange={e=>setQuery(e.target.value)}/>{['attendance','payslips','payruns'].includes(view)&&<Input type="month" aria-label="Record period" value={period} onChange={e=>setPeriod(e.target.value)}/>}<span className="spacer"/>{filterId&&<div className="screen-filter">{empName(filterId)}<button className="link" onClick={()=>setFilterId('')}>Clear filter</button></div>}{view==='employees'&&<><Button variant={mode==='grid'?'secondary':'outline'} onClick={()=>setMode('grid')} aria-label="Employee card view"><LayoutGrid/></Button><Button variant={mode==='list'?'secondary':'outline'} onClick={()=>setMode('list')} aria-label="Employee list view"><List/></Button></>}</div>}
 {view==='employees'&&(mode==='grid'?<div className="cards">{filtered(s.employees).map(e=><button key={e.id} className="employee-card" onClick={()=>navigate('employee',e.id)}><Avatar name={e.name}/><h2>{e.name}</h2><p>{e.position}</p><p>{e.email}</p><div><span className="tag">{e.department}</span><Badge value={e.status}/></div></button>)}{!filtered(s.employees).length&&<div className="empty">No employees match your search.</div>}</div>:<section className="panel table-panel"><DataTable rows={filtered(s.employees)} columns={[{title:'Employee',render:e=><button className="employee-cell link" onClick={()=>navigate('employee',e.id)}><Avatar name={e.name}/>{e.name}</button>},{title:'Work email',render:e=>e.email},{title:'Job position',render:e=>e.position},{title:'Department',render:e=>e.department},{title:'Status',render:e=><Badge value={e.status}/>}]} /></section>)}
 {view==='employee'&&(activeEmployee?<section className="panel"><div className="employee-cell"><Avatar name={activeEmployee.name}/><div><h2>{activeEmployee.position}</h2><p className="muted">{activeEmployee.email} · {activeEmployee.phone||'No phone added'}</p></div><Badge value={activeEmployee.status}/></div><div className="smart-buttons">{[['contracts','Contracts'],['attendance','Attendance'],['requests','Time off'],['allocations','Allocations']].map(([v,label])=><Button key={v} variant="outline" onClick={()=>related(v,activeEmployee.id)}>{label} <span className="count">{s[v as keyof Workspace].filter(r=>r.employeeId===activeEmployee.id).length}</span></Button>)}</div><h2>Work information</h2><dl className="detail-grid">{[['Department',activeEmployee.department],['Manager',activeEmployee.manager],['Working schedule',s.schedules.find(sc=>sc.id===activeEmployee.scheduleId)?.name],['Work location',activeEmployee.location],['Employee type',activeEmployee.type],['Company','OXP Pvt Ltd'],['Bank reference',activeEmployee.bank||'Missing — required to validate payroll']].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value||'Not set'}</dd></div>)}</dl><h2>Current leave balances</h2><div className="smart-buttons">{s.allocations.filter(a=>a.employeeId===activeEmployee.id&&a.status==='Approved').map(a=><span className="tag" key={a.id}>{leaveType(a.typeId)?.name}: {allocationBalance(s,a)} {leaveType(a.typeId)?.unit.toLowerCase()}</span>)}</div></section>:<div className="empty">Employee not found.</div>)}
 {view==='contracts'&&<section className="panel table-panel"><DataTable rows={filtered(s.contracts)} columns={[{title:'Contract',render:c=><button className="link" onClick={()=>openForm('contracts',c)}>{c.id.startsWith('c')&&c.id.length<5?'CON/2026/'+String(+c.id.slice(1)+1).padStart(4,'0'):c.id.slice(0,8).toUpperCase()}</button>},{title:'Employee',render:cellEmployee},{title:'Start date',render:c=>c.start},{title:'End date',render:c=>c.end||'Open-ended'},{title:'Monthly wage',render:c=>money(c.wage)},{title:'Structure',render:c=>structure(c.structureId)},{title:'Status',render:c=><Badge value={c.end&&c.end<clockNow.toISOString().slice(0,10)?'Expired':c.start>clockNow.toISOString().slice(0,10)?'Upcoming':'Running'}/>}]} /></section>}
 {view==='attendance'&&<section className="panel table-panel"><DataTable rows={filtered(s.attendance).filter(a=>!period||a.date.startsWith(period)).sort((a,b)=>b.date.localeCompare(a.date))} columns={[{title:'Employee',render:cellEmployee},{title:'Date',render:a=><button className="link" onClick={()=>openForm('attendance',a)}>{a.date}</button>},{title:'Check-in',render:a=>a.checkIn||'—'},{title:'Check-out',render:a=>a.checkOut||'—'},{title:'Worked hours',render:a=>hours(a).toFixed(2)},{title:'Status',render:a=><Badge value={attendanceStatus(a)}/>},{title:'Source',render:a=>a.edited?'Manually edited':'Attendance entry'}]}/></section>}
 {view==='requests'&&<section className="panel table-panel"><DataTable rows={filtered(s.requests)} columns={[{title:'Employee',render:cellEmployee},{title:'Time off type',render:r=><button className="link" onClick={()=>{setError('');setModal({kind:'request',record:r});}}>{leaveType(r.typeId)?.name}</button>},{title:'Dates',render:r=>r.start+' ? '+r.end},{title:'Duration',render:r=>r.duration+' '+leaveType(r.typeId)?.unit.toLowerCase()},{title:'Status',render:r=><Badge value={r.status}/>},{title:'Review',render:r=><button className="link" onClick={()=>{setError('');setModal({kind:'request',record:r});}}>Open <ArrowUpRight size={14}/></button>}]} /></section>}
 {view==='allocations'&&<section className="panel table-panel"><DataTable rows={filtered(s.allocations)} columns={[{title:'Employee',render:cellEmployee},{title:'Type',render:r=><button className="link" onClick={()=>setModal({kind:'allocation',record:r})}>{leaveType(r.typeId)?.name}</button>},{title:'Allocated',render:r=>r.amount+' '+leaveType(r.typeId)?.unit.toLowerCase()},{title:'Taken',render:r=>r.status==='Approved'?r.amount-allocationBalance(s,r):0},{title:'Remaining',render:r=>allocationBalance(s,r)},{title:'Validity',render:r=>r.start+' ? '+r.end},{title:'Status',render:r=><Badge value={r.status}/>}]} /></section>}
 {view==='leaveTypes'&&<section className="panel table-panel"><DataTable rows={filtered(s.leaveTypes)} columns={[{title:'Type',render:r=><button className="link" onClick={()=>openForm('leaveTypes',r)}>{r.name}</button>},{title:'Unit',render:r=>r.unit},{title:'Allocation',render:r=>r.requiresAllocation?'Required':'Not required'},{title:'Approval',render:()=> 'HR approval'},{title:'Status',render:()=> <Badge value="Active"/>}]} /></section>}
 {view==='schedules'&&<section className="panel table-panel"><DataTable rows={filtered(s.schedules)} columns={[{title:'Schedule',render:r=><button className="link" onClick={()=>openForm('schedules',r)}>{r.name}</button>},{title:'Working days',render:r=>r.days.map((d:string)=>d.slice(0,3)).join(', ')},{title:'Hours',render:r=>r.start+' – '+r.end},{title:'Daily break',render:r=>r.breakHours+' hr'},{title:'Weekly hours',render:r=>((hours({id:r.id,checkIn:r.start,checkOut:r.end})-r.breakHours)*r.days.length).toFixed(1)}]}/></section>}
 {view==='rules'&&<><p className="note">These are configurable example rules, not statutory tax or contribution calculations. Add a rule to a salary structure to use it in payroll.</p><section className="panel table-panel"><DataTable rows={filtered(s.rules).sort((a,b)=>a.sequence-b.sequence)} columns={[{title:'Rule name',render:r=><button className="link" onClick={()=>openForm('rules',r)}>{r.name}</button>},{title:'Code',render:r=><span className="tag">{r.code}</span>},{title:'Category',render:r=>r.category},{title:'Sequence',render:r=>r.sequence},{title:'Method',render:r=>r.method},{title:'Calculation',render:r=>r.method==='Formula'?r.expression:r.method==='Percentage'?r.value+'% × '+r.base:money(r.value)}]}/></section></>}
 {view==='structures'&&<section className="panel table-panel"><DataTable rows={filtered(s.structures)} columns={[{title:'Structure name',render:r=><button className="link" onClick={()=>openForm('structures',r)}>{r.name}</button>},{title:'Rules',render:r=>r.ruleIds.length+' rules'},{title:'Employees',render:r=>new Set(s.contracts.filter(c=>c.structureId===r.id&&c.start<=monthEnd(period)&&(!c.end||c.end>=period+'-01')).map(c=>c.employeeId)).size},{title:'Status',render:r=><Badge value={r.active?'Active':'Archived'}/>}]} /></section>}
 {view==='payruns'&&<section className="panel table-panel"><DataTable rows={filtered(s.payruns).filter(r=>!period||r.period===period).slice().reverse()} columns={[{title:'Payrun',render:r=><button className="link" onClick={()=>navigate('run',r.id)}>{r.name}<ArrowUpRight size={14}/></button>},{title:'Period',render:r=>r.period+'-01 ? '+monthEnd(r.period)},{title:'Structure',render:r=>structure(r.structureId)},{title:'Employees',render:r=>r.employeeIds.length},{title:'Net salary',render:r=>money(r.slips.reduce((n:number,p:Row)=>n+p.net,0))},{title:'Status',render:r=><Badge value={r.status}/>},{title:'Warnings',render:r=>r.status==='Paid'?'Finalized':warnings(s,r).length||'None'}]} /></section>}
 {view==='run'&&(run?<><section className="panel"><div className="panel-head"><h2>Payrun processing</h2><Badge value={run.status}/></div><div className="run-summary"><div><small>Period</small><strong>{run.period+'-01'} — {monthEnd(run.period)}</strong></div><div><small>Salary structure</small><strong>{structure(run.structureId)}</strong></div><div><small>Selected employees</small><strong>{run.employeeIds.length}</strong></div><div><small>Net salary</small><strong>{money(run.slips.reduce((n:number,p:Row)=>n+p.net,0))}</strong></div></div><div className="smart-buttons"><Button disabled={busy||!['Draft','Computed'].includes(run.status)} onClick={()=>void act('compute',{id:run.id},'Payslips computed from the selected salary rules.')}><RefreshCw/> Compute</Button><Button variant="outline" disabled={busy||run.status!=='Computed'} onClick={()=>void act('validate',{id:run.id},'Payrun validated. Salary snapshots are now locked.')}><Check/> Validate</Button><Button variant="outline" disabled={busy||run.status!=='Validated'} onClick={()=>void act('markPaid',{id:run.id},'Payrun marked paid. No bank transfer was initiated.')}>Mark paid</Button><Button variant="outline" disabled={!run.slips.length} onClick={()=>downloadCsv('payslips-'+run.period+'.csv',[['Employee','Period','Basic','Gross','Deductions','Net'],...run.slips.map((p:Row)=>[empName(p.employeeId),p.period,p.basic,p.gross,p.deductions,p.net])])}><Download/> Export payslips</Button></div>{!['Validated','Paid'].includes(run.status)&&warnings(s,run).length>0&&<div className="warning-box"><b>Resolve before validation</b>{warnings(s,run).map(w=><p key={w}>{w}</p>)}<button className="link" onClick={()=>navigate('employees')}>Open employee records <ArrowUpRight size={14}/></button></div>}<p className="muted">Mark paid records a payment status only. Email delivery and bank transfers are not connected.</p></section><section className="panel table-panel" style={{marginTop:22}}><div className="panel-head"><h2>Payslips in this payrun</h2><span className="muted">{run.slips.length} generated</span></div><DataTable rows={run.slips} columns={runSlipColumns} empty="Click Compute to generate payslips from the employees’ contracts and salary rules."/></section></>:<div className="empty">Payrun not found.</div>)}
 {view==='payslips'&&<section className="panel table-panel"><DataTable rows={filtered(allSlips).filter(p=>!period||p.period===period)} columns={[{title:'Period',render:p=>niceMonth(p.period)},...runSlipColumns.slice(0,-1),{title:'Status',render:p=><Badge value={p.status}/>} ,runSlipColumns.at(-1)!]}/></section>}
 </>}
 <footer><span className="live-dot"/>Sample company · Demo admin workspace<span>PeoplePay360 · HR & Payroll</span></footer></main>
 <Dialog open={!!modal} onOpenChange={open=>{if(!open&&!busy){setModal(null);setError('');}}}><DialogContent className="modal"><DialogTitle>{modal?.kind==='form'?(modal.record?.id?'Edit ':'New ')+(titles[modal.collection!]||'record'):modal?.kind==='wizard'?'New payrun':modal?.kind==='slip'?'Employee payslip':modal?.kind==='clock'?'Your attendance':modal?.kind==='about'?'About this prototype':modal?.kind==='allocation'?'Leave allocation':'Time off request'}</DialogTitle><DialogDescription>{modal?.kind==='about'?'PeoplePay360 · OXP sample company':modal?.kind==='clock'?'Nisha Rao · Finance Manager':modal?.kind==='wizard'?'Choose the payroll period, then select eligible employees.':'Connected to your PeoplePay workspace.'}</DialogDescription>
 {error&&<div className="error" role="alert">{error}</div>}
 {modal?.kind==='form'&&s&&<RecordForm key={modal.collection+modal.record!.id} collection={modal.collection!} initial={modal.record!} s={s} busy={busy} onSave={saveRecord} onCancel={()=>setModal(null)}/>}
 {modal?.kind==='wizard'&&s&&<PayrunWizard s={s} busy={busy} onCancel={()=>setModal(null)} onCreate={async p=>{const result=await act('createPayrun',p,'Payrun created.');if(result){const created=result.payruns.at(-1)!;setPeriod(created.period);navigate('run',created.id);}}}/>}
 {(modal?.kind==='request'||modal?.kind==='allocation')&&reviewedRecord&&<><div className="employee-cell"><Avatar name={empName(reviewedRecord.employeeId)}/><div><h2>{empName(reviewedRecord.employeeId)}</h2><p className="muted">{leaveType(reviewedRecord.typeId)?.name}</p></div><Badge value={reviewedRecord.status}/></div><dl className="detail-grid">{[['Start',reviewedRecord.start],['End',reviewedRecord.end],['Amount',(reviewedRecord.duration||reviewedRecord.amount)+' '+leaveType(reviewedRecord.typeId)?.unit.toLowerCase()],['Approver',reviewedRecord.approver||'Awaiting review']].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl>{reviewedRecord.reason&&<p className="note">{reviewedRecord.reason}</p>}{modal.kind==='allocation'&&s&&<div className="total">Available balance <strong>{allocationBalance(s,reviewedRecord)}</strong></div>}<div className="modal-actions">{reviewedRecord.status==='Pending'&&<><Button variant="outline" disabled={busy} onClick={()=>openForm(modal.kind==='request'?'requests':'allocations',reviewedRecord)}>Edit</Button>{modal.kind==='request'&&<Button variant="outline" disabled={busy} onClick={()=>void act('refuseLeave',{id:reviewedRecord.id},'Request refused.')}>Refuse</Button>}<Button disabled={busy} onClick={()=>void act(modal.kind==='request'?'approveLeave':'approveAllocation',{id:reviewedRecord.id},'Approved.')}>Approve</Button></>}<Button variant="outline" onClick={()=>setModal(null)}>Close</Button></div></>}
 {modal?.kind==='slip'&&<><div className="slip-heading"><div><p className="eyebrow">OXP PVT LTD</p><h2>{empName(modal.record!.employeeId)}</h2><p className="muted">{niceMonth(modal.record!.period)} · {structure(modal.record!.structureId)}</p></div><Badge value={modal.record!.status||s?.payruns.find(r=>r.slips.some((p:Row)=>p.id===modal.record!.id))?.status||'Computed'}/></div><p className="muted">{employee(modal.record!.employeeId)?.department} · {modal.record!.workedDays} recorded attendance days</p><DataTable rows={modal.record!.lines.map((l:any)=>({...l,id:l.code}))} columns={[{title:'Salary component',render:l=>l.name},{title:'Category',render:l=>l.category},{title:'Amount',render:l=>(l.category==='Deduction'?'- ':'')+money(l.amount)}]}/><div className="run-summary"><div><small>Gross salary</small><strong>{money(modal.record!.gross)}</strong></div><div><small>Total deductions</small><strong>{money(modal.record!.deductions)}</strong></div></div><div className="total"><span>Net salary</span><strong>{money(modal.record!.net)}</strong></div><p className="note">Prototype payslip using example rules. Attendance days are displayed for context; automatic absence deductions and statutory compliance are not implemented.</p><div className="modal-actions"><Button variant="outline" onClick={()=>setModal(null)}>Close</Button><Button onClick={()=>window.print()}><Download/> Print / Save PDF</Button></div></>}
 {modal?.kind==='clock'&&<><div className="time-display">{clockNow.toLocaleTimeString('en-IN',{timeZone:'Asia/Kolkata',hour:'2-digit',minute:'2-digit'})}</div><p className="muted" style={{textAlign:'center'}}>Today · {clockNow.toLocaleDateString('en-IN',{timeZone:'Asia/Kolkata',day:'numeric',month:'long'})} · Asia/Kolkata</p><div className="total"><span>{signedIn?'Checked in at '+currentClock?.checkIn:currentClock?.checkOut?'Today’s attendance complete':'You are not checked in'}</span><Badge value={signedIn?'Present':currentClock?.checkOut?'Completed':'Not checked in'}/></div>{signedIn&&<p className="muted">Elapsed: {Math.max(0,Math.floor((Date.parse(clockNow.toLocaleDateString('en-CA',{timeZone:'Asia/Kolkata'})+'T'+clockNow.toLocaleTimeString('en-GB',{timeZone:'Asia/Kolkata',hour12:false})+'+05:30')-Date.parse(currentClock.date+'T'+currentClock.checkIn+':00+05:30'))/60000))} minutes</p>}<div className="modal-actions"><Button variant="outline" onClick={()=>navigate('attendance')}>View records</Button><Button disabled={busy||!!currentClock?.checkOut||!s} onClick={()=>void act('clock',{employeeId:'e6'},signedIn?'Checked out.':'Checked in.')}>{signedIn?'Check out':'Check in'}</Button></div></>}
 {modal?.kind==='about'&&<><p className="note">This first prototype opens as a demo administrator. All people and bank references are fictional. It includes persistent records, employee profiles, attendance, leave approval, and configurable payroll.</p><p className="note">Account login and role enforcement, real email delivery, statutory payroll, partial-month contracts, and automatic attendance-based deductions are planned follow-ups. No money or email is sent by this application.</p><Button variant="outline" onClick={()=>setModal(null)}>Back to workspace</Button></>}
 </DialogContent></Dialog></>;
}

function PayrunWizard({s,busy,onCreate,onCancel}:{s:Workspace;busy:boolean;onCreate:(p:Record<string,any>)=>Promise<void>;onCancel:()=>void}){
 const [step,setStep]=useState(1),[period,setPeriod]=useState('2026-10'),[structureId,setStructureId]=useState(s.structures[0]?.id||''),[ids,setIds]=useState<string[]>([]),[search,setSearch]=useState('');
 const eligible=s.employees.filter(e=>{if(e.status!=='Active'||!/^\d{4}-(0[1-9]|1[0-2])$/.test(period))return false;try{const c=activeContract(s,e.id,period);return c.structureId===structureId&&!s.payruns.some(r=>r.period===period&&r.employeeIds.includes(e.id));}catch{return false;}});
 const toggle=(id:string,checked:boolean)=>setIds(x=>checked?[...x,id]:x.filter(i=>i!==id));
 return <><div className="steps"><span className={step===1?'current':''}>01 · Scope & period</span><span className={step===2?'current':''}>02 · Select employees</span></div>{step===1?<div className="form-grid"><Field label="Salary structure"><Picker label="Salary structure" value={structureId} onChange={setStructureId} options={s.structures.filter(st=>st.active).map(st=>({value:st.id,label:st.name}))}/></Field><Field label="Payroll month"><Input type="month" required aria-label="Payroll month" value={period} onChange={e=>setPeriod(e.target.value)}/></Field><p className="note field wide">Only active employees with a full-period contract matching this structure can be selected. Employees already included in this month’s payroll are excluded.</p></div>:<><div className="toolbar"><Input aria-label="Search eligible employees" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search eligible employees…"/><span className="tag">{ids.length} selected</span></div><div className="check-list"><label><Checkbox checked={eligible.length>0&&ids.length===eligible.length} onCheckedChange={v=>setIds(v?eligible.map(e=>e.id):[])}/>Select all eligible employees</label>{eligible.filter(e=>e.name.toLowerCase().includes(search.toLowerCase())).map(e=><label key={e.id}><Checkbox checked={ids.includes(e.id)} onCheckedChange={v=>toggle(e.id,!!v)}/><Avatar name={e.name}/>{e.name}<small>{e.department}{!e.bank?' · Bank missing':''}</small></label>)}{!eligible.length&&<div className="empty">No eligible employees. Check contract dates, the salary structure, or existing payruns.</div>}</div></> }<div className="modal-actions"><Button variant="outline" onClick={step===1?onCancel:()=>setStep(1)}>{step===1?'Cancel':'Back'}</Button>{step===1?<Button disabled={!structureId||!/^\d{4}-(0[1-9]|1[0-2])$/.test(period)} onClick={()=>{setIds([]);setStep(2);}}>Continue <ArrowUpRight/></Button>:<Button disabled={busy||!ids.length} onClick={()=>void onCreate({period,structureId,employeeIds:ids})}>{busy?'Creating…':'Create payrun'}</Button>}</div></>;
}

