import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';
import type { Row } from './domain';

const amount = (value: number) => `INR ${Number(value || 0).toLocaleString('en-IN', { maximumFractionDigits: 2 })}`;

export async function createPayslipPdf(employee: Row, slip: Row, structureName: string) {
  const pdf = await PDFDocument.create();
  const page = pdf.addPage([595.28, 841.89]);
  const regular = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);
  const dark = rgb(0.08, 0.1, 0.15);
  let y = 790;
  const draw = (text: string, size = 10, isBold = false, x = 48) => {
    page.drawText(text, { x, y, size, font: isBold ? bold : regular, color: dark });
    y -= size + 9;
  };

  draw('PEOPLEPAY360', 10, true);
  draw('OXP PVT LTD', 18, true);
  draw(`Payslip for ${slip.period}`, 12);
  y -= 12;
  draw(employee.name, 16, true);
  draw(`${employee.position || 'Employee'} | ${employee.department || ''}`);
  draw(employee.email || '');
  draw(`Salary structure: ${structureName}`);
  draw(`Recorded worked days: ${slip.workedDays || 0}`);
  draw(`Scheduled days: ${slip.scheduledDays || 0} | Payable days: ${slip.payableDays || 0}`);
  if (slip.unpaidLeaveDays) draw(`Unpaid leave: ${slip.unpaidLeaveDays} day(s)`);
  y -= 16;
  draw('SALARY COMPONENTS', 11, true);
  page.drawLine({ start: { x: 48, y: y + 5 }, end: { x: 547, y: y + 5 }, thickness: 1, color: rgb(0.85, 0.85, 0.85) });

  for (const line of slip.lines || []) {
    page.drawText(String(line.name), { x: 48, y, size: 10, font: regular, color: dark });
    page.drawText(String(line.category), { x: 300, y, size: 9, font: regular, color: rgb(0.35, 0.38, 0.45) });
    const rendered = `${line.category === 'Deduction' ? '- ' : ''}${amount(line.amount)}`;
    page.drawText(rendered, { x: 430, y, size: 10, font: regular, color: dark });
    y -= 24;
  }

  y -= 10;
  page.drawRectangle({ x: 48, y: y - 60, width: 499, height: 74, color: dark });
  page.drawText('Gross salary', { x: 64, y: y - 10, size: 10, font: regular, color: rgb(1, 1, 1) });
  page.drawText(amount(slip.gross), { x: 410, y: y - 10, size: 10, font: bold, color: rgb(1, 1, 1) });
  page.drawText('Deductions', { x: 64, y: y - 30, size: 10, font: regular, color: rgb(1, 1, 1) });
  page.drawText(amount(slip.deductions), { x: 410, y: y - 30, size: 10, font: bold, color: rgb(1, 1, 1) });
  page.drawText('NET SALARY', { x: 64, y: y - 51, size: 12, font: bold, color: rgb(1, 1, 1) });
  page.drawText(amount(slip.net), { x: 410, y: y - 51, size: 12, font: bold, color: rgb(1, 1, 1) });
  page.drawText('Generated by PeoplePay360', { x: 48, y: 42, size: 8, font: regular, color: rgb(0.5, 0.5, 0.5) });

  return pdf.save();
}
